<?php
/**
 * CreateWebinarSettings
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * The Zoom API allows developers to safely and securely access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developersupport@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Weble\Zoom\Model;

use \ArrayAccess;
use \Weble\Zoom\ObjectSerializer;

/**
 * CreateWebinarSettings Class Doc Comment
 *
 * @category Class
 * @description Create Webinar settings.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CreateWebinarSettings implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'create_webinar_settings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'host_video' => 'bool',
        'panelists_video' => 'bool',
        'practice_session' => 'bool',
        'hd_video' => 'bool',
        'approval_type' => 'int',
        'registration_type' => 'int',
        'audio' => 'string',
        'auto_recording' => 'string',
        'enforce_login' => 'bool',
        'enforce_login_domains' => 'string',
        'alternative_hosts' => 'string',
        'close_registration' => 'bool',
        'show_share_button' => 'bool',
        'allow_multiple_devices' => 'bool',
        'on_demand' => 'bool',
        'global_dial_in_countries' => 'string[]',
        'contact_name' => 'string',
        'contact_email' => 'string',
        'registrants_restrict_number' => 'int',
        'post_webinar_survey' => 'bool',
        'survey_url' => 'string',
        'registrants_email_notification' => 'bool',
        'meeting_authentication' => 'bool',
        'authentication_option' => 'string',
        'authentication_domains' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'host_video' => null,
        'panelists_video' => null,
        'practice_session' => null,
        'hd_video' => null,
        'approval_type' => null,
        'registration_type' => null,
        'audio' => null,
        'auto_recording' => null,
        'enforce_login' => null,
        'enforce_login_domains' => null,
        'alternative_hosts' => null,
        'close_registration' => null,
        'show_share_button' => null,
        'allow_multiple_devices' => null,
        'on_demand' => null,
        'global_dial_in_countries' => null,
        'contact_name' => null,
        'contact_email' => null,
        'registrants_restrict_number' => null,
        'post_webinar_survey' => null,
        'survey_url' => null,
        'registrants_email_notification' => null,
        'meeting_authentication' => null,
        'authentication_option' => null,
        'authentication_domains' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'host_video' => 'host_video',
        'panelists_video' => 'panelists_video',
        'practice_session' => 'practice_session',
        'hd_video' => 'hd_video',
        'approval_type' => 'approval_type',
        'registration_type' => 'registration_type',
        'audio' => 'audio',
        'auto_recording' => 'auto_recording',
        'enforce_login' => 'enforce_login',
        'enforce_login_domains' => 'enforce_login_domains',
        'alternative_hosts' => 'alternative_hosts',
        'close_registration' => 'close_registration',
        'show_share_button' => 'show_share_button',
        'allow_multiple_devices' => 'allow_multiple_devices',
        'on_demand' => 'on_demand',
        'global_dial_in_countries' => 'global_dial_in_countries',
        'contact_name' => 'contact_name',
        'contact_email' => 'contact_email',
        'registrants_restrict_number' => 'registrants_restrict_number',
        'post_webinar_survey' => 'post_webinar_survey',
        'survey_url' => 'survey_url',
        'registrants_email_notification' => 'registrants_email_notification',
        'meeting_authentication' => 'meeting_authentication',
        'authentication_option' => 'authentication_option',
        'authentication_domains' => 'authentication_domains'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'host_video' => 'setHostVideo',
        'panelists_video' => 'setPanelistsVideo',
        'practice_session' => 'setPracticeSession',
        'hd_video' => 'setHdVideo',
        'approval_type' => 'setApprovalType',
        'registration_type' => 'setRegistrationType',
        'audio' => 'setAudio',
        'auto_recording' => 'setAutoRecording',
        'enforce_login' => 'setEnforceLogin',
        'enforce_login_domains' => 'setEnforceLoginDomains',
        'alternative_hosts' => 'setAlternativeHosts',
        'close_registration' => 'setCloseRegistration',
        'show_share_button' => 'setShowShareButton',
        'allow_multiple_devices' => 'setAllowMultipleDevices',
        'on_demand' => 'setOnDemand',
        'global_dial_in_countries' => 'setGlobalDialInCountries',
        'contact_name' => 'setContactName',
        'contact_email' => 'setContactEmail',
        'registrants_restrict_number' => 'setRegistrantsRestrictNumber',
        'post_webinar_survey' => 'setPostWebinarSurvey',
        'survey_url' => 'setSurveyUrl',
        'registrants_email_notification' => 'setRegistrantsEmailNotification',
        'meeting_authentication' => 'setMeetingAuthentication',
        'authentication_option' => 'setAuthenticationOption',
        'authentication_domains' => 'setAuthenticationDomains'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'host_video' => 'getHostVideo',
        'panelists_video' => 'getPanelistsVideo',
        'practice_session' => 'getPracticeSession',
        'hd_video' => 'getHdVideo',
        'approval_type' => 'getApprovalType',
        'registration_type' => 'getRegistrationType',
        'audio' => 'getAudio',
        'auto_recording' => 'getAutoRecording',
        'enforce_login' => 'getEnforceLogin',
        'enforce_login_domains' => 'getEnforceLoginDomains',
        'alternative_hosts' => 'getAlternativeHosts',
        'close_registration' => 'getCloseRegistration',
        'show_share_button' => 'getShowShareButton',
        'allow_multiple_devices' => 'getAllowMultipleDevices',
        'on_demand' => 'getOnDemand',
        'global_dial_in_countries' => 'getGlobalDialInCountries',
        'contact_name' => 'getContactName',
        'contact_email' => 'getContactEmail',
        'registrants_restrict_number' => 'getRegistrantsRestrictNumber',
        'post_webinar_survey' => 'getPostWebinarSurvey',
        'survey_url' => 'getSurveyUrl',
        'registrants_email_notification' => 'getRegistrantsEmailNotification',
        'meeting_authentication' => 'getMeetingAuthentication',
        'authentication_option' => 'getAuthenticationOption',
        'authentication_domains' => 'getAuthenticationDomains'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const AUDIO_BOTH = 'both';
    const AUDIO_TELEPHONY = 'telephony';
    const AUDIO_VOIP = 'voip';
    const AUTO_RECORDING_LOCAL = 'local';
    const AUTO_RECORDING_CLOUD = 'cloud';
    const AUTO_RECORDING_NONE = 'none';



    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAudioAllowableValues()
    {
        return [
            self::AUDIO_BOTH,
            self::AUDIO_TELEPHONY,
            self::AUDIO_VOIP,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAutoRecordingAllowableValues()
    {
        return [
            self::AUTO_RECORDING_LOCAL,
            self::AUTO_RECORDING_CLOUD,
            self::AUTO_RECORDING_NONE,
        ];
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['host_video'] = isset($data['host_video']) ? $data['host_video'] : null;
        $this->container['panelists_video'] = isset($data['panelists_video']) ? $data['panelists_video'] : null;
        $this->container['practice_session'] = isset($data['practice_session']) ? $data['practice_session'] : false;
        $this->container['hd_video'] = isset($data['hd_video']) ? $data['hd_video'] : false;
        $this->container['approval_type'] = isset($data['approval_type']) ? $data['approval_type'] : null;
        $this->container['registration_type'] = isset($data['registration_type']) ? $data['registration_type'] : null;
        $this->container['audio'] = isset($data['audio']) ? $data['audio'] : 'both';
        $this->container['auto_recording'] = isset($data['auto_recording']) ? $data['auto_recording'] : 'none';
        $this->container['enforce_login'] = isset($data['enforce_login']) ? $data['enforce_login'] : null;
        $this->container['enforce_login_domains'] = isset($data['enforce_login_domains']) ? $data['enforce_login_domains'] : null;
        $this->container['alternative_hosts'] = isset($data['alternative_hosts']) ? $data['alternative_hosts'] : null;
        $this->container['close_registration'] = isset($data['close_registration']) ? $data['close_registration'] : null;
        $this->container['show_share_button'] = isset($data['show_share_button']) ? $data['show_share_button'] : null;
        $this->container['allow_multiple_devices'] = isset($data['allow_multiple_devices']) ? $data['allow_multiple_devices'] : null;
        $this->container['on_demand'] = isset($data['on_demand']) ? $data['on_demand'] : false;
        $this->container['global_dial_in_countries'] = isset($data['global_dial_in_countries']) ? $data['global_dial_in_countries'] : null;
        $this->container['contact_name'] = isset($data['contact_name']) ? $data['contact_name'] : null;
        $this->container['contact_email'] = isset($data['contact_email']) ? $data['contact_email'] : null;
        $this->container['registrants_restrict_number'] = isset($data['registrants_restrict_number']) ? $data['registrants_restrict_number'] : null;
        $this->container['post_webinar_survey'] = isset($data['post_webinar_survey']) ? $data['post_webinar_survey'] : null;
        $this->container['survey_url'] = isset($data['survey_url']) ? $data['survey_url'] : null;
        $this->container['registrants_email_notification'] = isset($data['registrants_email_notification']) ? $data['registrants_email_notification'] : null;
        $this->container['meeting_authentication'] = isset($data['meeting_authentication']) ? $data['meeting_authentication'] : null;
        $this->container['authentication_option'] = isset($data['authentication_option']) ? $data['authentication_option'] : null;
        $this->container['authentication_domains'] = isset($data['authentication_domains']) ? $data['authentication_domains'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getAudioAllowableValues();
        if (!is_null($this->container['audio']) && !in_array($this->container['audio'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'audio', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getAutoRecordingAllowableValues();
        if (!is_null($this->container['auto_recording']) && !in_array($this->container['auto_recording'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'auto_recording', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['registrants_restrict_number']) && ($this->container['registrants_restrict_number'] > 20000)) {
            $invalidProperties[] = "invalid value for 'registrants_restrict_number', must be smaller than or equal to 20000.";
        }

        if (!is_null($this->container['registrants_restrict_number']) && ($this->container['registrants_restrict_number'] < 0)) {
            $invalidProperties[] = "invalid value for 'registrants_restrict_number', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets host_video
     *
     * @return bool
     */
    public function getHostVideo()
    {
        return $this->container['host_video'];
    }

    /**
     * Sets host_video
     *
     * @param bool $host_video Start video when host joins webinar.
     *
     * @return $this
     */
    public function setHostVideo($host_video)
    {
        $this->container['host_video'] = $host_video;

        return $this;
    }

    /**
     * Gets panelists_video
     *
     * @return bool
     */
    public function getPanelistsVideo()
    {
        return $this->container['panelists_video'];
    }

    /**
     * Sets panelists_video
     *
     * @param bool $panelists_video Start video when panelists join webinar.
     *
     * @return $this
     */
    public function setPanelistsVideo($panelists_video)
    {
        $this->container['panelists_video'] = $panelists_video;

        return $this;
    }

    /**
     * Gets practice_session
     *
     * @return bool
     */
    public function getPracticeSession()
    {
        return $this->container['practice_session'];
    }

    /**
     * Sets practice_session
     *
     * @param bool $practice_session Enable practice session.
     *
     * @return $this
     */
    public function setPracticeSession($practice_session)
    {
        $this->container['practice_session'] = $practice_session;

        return $this;
    }

    /**
     * Gets hd_video
     *
     * @return bool
     */
    public function getHdVideo()
    {
        return $this->container['hd_video'];
    }

    /**
     * Sets hd_video
     *
     * @param bool $hd_video Default to HD video.
     *
     * @return $this
     */
    public function setHdVideo($hd_video)
    {
        $this->container['hd_video'] = $hd_video;

        return $this;
    }

    /**
     * Gets approval_type
     *
     * @return int
     */
    public function getApprovalType()
    {
        return $this->container['approval_type'];
    }

    /**
     * Sets approval_type
     *
     * @param int $approval_type `0` - Automatically approve.<br>`1` - Manually approve.<br>`2` - No registration required.
     *
     * @return $this
     */
    public function setApprovalType($approval_type)
    {
        $this->container['approval_type'] = $approval_type;

        return $this;
    }

    /**
     * Gets registration_type
     *
     * @return int
     */
    public function getRegistrationType()
    {
        return $this->container['registration_type'];
    }

    /**
     * Sets registration_type
     *
     * @param int $registration_type Registration types. Only used for recurring webinars with a fixed time.<br>`1` - Attendees register once and can attend any of the webinar sessions.<br>`2` - Attendees need to register for each session in order to attend.<br>`3` - Attendees register once and can choose one or more sessions to attend.
     *
     * @return $this
     */
    public function setRegistrationType($registration_type)
    {
        $this->container['registration_type'] = $registration_type;

        return $this;
    }

    /**
     * Gets audio
     *
     * @return string
     */
    public function getAudio()
    {
        return $this->container['audio'];
    }

    /**
     * Sets audio
     *
     * @param string $audio Determine how participants can join the audio portion of the meeting.
     *
     * @return $this
     */
    public function setAudio($audio)
    {
        $allowedValues = $this->getAudioAllowableValues();
        if (!is_null($audio) && !in_array($audio, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'audio', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['audio'] = $audio;

        return $this;
    }

    /**
     * Gets auto_recording
     *
     * @return string
     */
    public function getAutoRecording()
    {
        return $this->container['auto_recording'];
    }

    /**
     * Sets auto_recording
     *
     * @param string $auto_recording Automatic recording:<br>`local` - Record on local.<br>`cloud` -  Record on cloud.<br>`none` - Disabled.
     *
     * @return $this
     */
    public function setAutoRecording($auto_recording)
    {
        $allowedValues = $this->getAutoRecordingAllowableValues();
        if (!is_null($auto_recording) && !in_array($auto_recording, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'auto_recording', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['auto_recording'] = $auto_recording;

        return $this;
    }

    /**
     * Gets enforce_login
     *
     * @return bool
     */
    public function getEnforceLogin()
    {
        return $this->container['enforce_login'];
    }

    /**
     * Sets enforce_login
     *
     * @param bool $enforce_login Only signed-in users can join this meeting.   **This field is deprecated and will not be supported in future.** <br><br> Instead of this field, use the \"meeting_authentication\", \"authentication_option\" and/or \"authentication_domains\" fields to establish the authentication mechanism for this Webinar.
     *
     * @return $this
     */
    public function setEnforceLogin($enforce_login)
    {
        $this->container['enforce_login'] = $enforce_login;

        return $this;
    }

    /**
     * Gets enforce_login_domains
     *
     * @return string
     */
    public function getEnforceLoginDomains()
    {
        return $this->container['enforce_login_domains'];
    }

    /**
     * Sets enforce_login_domains
     *
     * @param string $enforce_login_domains Only signed-in users with specified domains can join meetings.  **This field is deprecated and will not be supported in future.** <br><br> Instead of this field, use the \"authentication_domains\" field for this Webinar.
     *
     * @return $this
     */
    public function setEnforceLoginDomains($enforce_login_domains)
    {
        $this->container['enforce_login_domains'] = $enforce_login_domains;

        return $this;
    }

    /**
     * Gets alternative_hosts
     *
     * @return string
     */
    public function getAlternativeHosts()
    {
        return $this->container['alternative_hosts'];
    }

    /**
     * Sets alternative_hosts
     *
     * @param string $alternative_hosts Alternative host emails or IDs. Multiple values separated by comma.
     *
     * @return $this
     */
    public function setAlternativeHosts($alternative_hosts)
    {
        $this->container['alternative_hosts'] = $alternative_hosts;

        return $this;
    }

    /**
     * Gets close_registration
     *
     * @return bool
     */
    public function getCloseRegistration()
    {
        return $this->container['close_registration'];
    }

    /**
     * Sets close_registration
     *
     * @param bool $close_registration Close registration after event date.
     *
     * @return $this
     */
    public function setCloseRegistration($close_registration)
    {
        $this->container['close_registration'] = $close_registration;

        return $this;
    }

    /**
     * Gets show_share_button
     *
     * @return bool
     */
    public function getShowShareButton()
    {
        return $this->container['show_share_button'];
    }

    /**
     * Sets show_share_button
     *
     * @param bool $show_share_button Show social share buttons on the registration page.
     *
     * @return $this
     */
    public function setShowShareButton($show_share_button)
    {
        $this->container['show_share_button'] = $show_share_button;

        return $this;
    }

    /**
     * Gets allow_multiple_devices
     *
     * @return bool
     */
    public function getAllowMultipleDevices()
    {
        return $this->container['allow_multiple_devices'];
    }

    /**
     * Sets allow_multiple_devices
     *
     * @param bool $allow_multiple_devices Allow attendees to join from multiple devices.
     *
     * @return $this
     */
    public function setAllowMultipleDevices($allow_multiple_devices)
    {
        $this->container['allow_multiple_devices'] = $allow_multiple_devices;

        return $this;
    }

    /**
     * Gets on_demand
     *
     * @return bool
     */
    public function getOnDemand()
    {
        return $this->container['on_demand'];
    }

    /**
     * Sets on_demand
     *
     * @param bool $on_demand Make the webinar on-demand
     *
     * @return $this
     */
    public function setOnDemand($on_demand)
    {
        $this->container['on_demand'] = $on_demand;

        return $this;
    }

    /**
     * Gets global_dial_in_countries
     *
     * @return string[]
     */
    public function getGlobalDialInCountries()
    {
        return $this->container['global_dial_in_countries'];
    }

    /**
     * Sets global_dial_in_countries
     *
     * @param string[] $global_dial_in_countries List of global dial-in countries
     *
     * @return $this
     */
    public function setGlobalDialInCountries($global_dial_in_countries)
    {
        $this->container['global_dial_in_countries'] = $global_dial_in_countries;

        return $this;
    }

    /**
     * Gets contact_name
     *
     * @return string
     */
    public function getContactName()
    {
        return $this->container['contact_name'];
    }

    /**
     * Sets contact_name
     *
     * @param string $contact_name Contact name for registration
     *
     * @return $this
     */
    public function setContactName($contact_name)
    {
        $this->container['contact_name'] = $contact_name;

        return $this;
    }

    /**
     * Gets contact_email
     *
     * @return string
     */
    public function getContactEmail()
    {
        return $this->container['contact_email'];
    }

    /**
     * Sets contact_email
     *
     * @param string $contact_email Contact email for registration
     *
     * @return $this
     */
    public function setContactEmail($contact_email)
    {
        $this->container['contact_email'] = $contact_email;

        return $this;
    }

    /**
     * Gets registrants_restrict_number
     *
     * @return int
     */
    public function getRegistrantsRestrictNumber()
    {
        return $this->container['registrants_restrict_number'];
    }

    /**
     * Sets registrants_restrict_number
     *
     * @param int $registrants_restrict_number Restrict number of registrants for a webinar. By default, it is set to `0`. A `0` value means that the restriction option is disabled. Provide a number higher than 0 to restrict the webinar registrants by the that number.
     *
     * @return $this
     */
    public function setRegistrantsRestrictNumber($registrants_restrict_number)
    {

        if (!is_null($registrants_restrict_number) && ($registrants_restrict_number > 20000)) {
            throw new \InvalidArgumentException('invalid value for $registrants_restrict_number when calling CreateWebinarSettings., must be smaller than or equal to 20000.');
        }
        if (!is_null($registrants_restrict_number) && ($registrants_restrict_number < 0)) {
            throw new \InvalidArgumentException('invalid value for $registrants_restrict_number when calling CreateWebinarSettings., must be bigger than or equal to 0.');
        }

        $this->container['registrants_restrict_number'] = $registrants_restrict_number;

        return $this;
    }

    /**
     * Gets post_webinar_survey
     *
     * @return bool
     */
    public function getPostWebinarSurvey()
    {
        return $this->container['post_webinar_survey'];
    }

    /**
     * Sets post_webinar_survey
     *
     * @param bool $post_webinar_survey Zoom will open a survey page in attendees' browsers after leaving the webinar
     *
     * @return $this
     */
    public function setPostWebinarSurvey($post_webinar_survey)
    {
        $this->container['post_webinar_survey'] = $post_webinar_survey;

        return $this;
    }

    /**
     * Gets survey_url
     *
     * @return string
     */
    public function getSurveyUrl()
    {
        return $this->container['survey_url'];
    }

    /**
     * Sets survey_url
     *
     * @param string $survey_url Survey url for post webinar survey
     *
     * @return $this
     */
    public function setSurveyUrl($survey_url)
    {
        $this->container['survey_url'] = $survey_url;

        return $this;
    }

    /**
     * Gets registrants_email_notification
     *
     * @return bool
     */
    public function getRegistrantsEmailNotification()
    {
        return $this->container['registrants_email_notification'];
    }

    /**
     * Sets registrants_email_notification
     *
     * @param bool $registrants_email_notification Send email notifications to registrants about approval, cancellation, denial of the registration. The value of this field must be set to true in order to use the `registrants_confirmation_email` field.
     *
     * @return $this
     */
    public function setRegistrantsEmailNotification($registrants_email_notification)
    {
        $this->container['registrants_email_notification'] = $registrants_email_notification;

        return $this;
    }

    /**
     * Gets meeting_authentication
     *
     * @return bool
     */
    public function getMeetingAuthentication()
    {
        return $this->container['meeting_authentication'];
    }

    /**
     * Sets meeting_authentication
     *
     * @param bool $meeting_authentication Only [authenticated](https://support.zoom.us/hc/en-us/articles/360037117472-Authentication-Profiles-for-Meetings-and-Webinars) users can join meeting if the value of this field is set to `true`.
     *
     * @return $this
     */
    public function setMeetingAuthentication($meeting_authentication)
    {
        $this->container['meeting_authentication'] = $meeting_authentication;

        return $this;
    }

    /**
     * Gets authentication_option
     *
     * @return string
     */
    public function getAuthenticationOption()
    {
        return $this->container['authentication_option'];
    }

    /**
     * Sets authentication_option
     *
     * @param string $authentication_option Specify the authentication type for users to join a Webinar with`meeting_authentication` setting set to `true`. The value of this field can be retrieved from the `id` field within `authentication_options` array in the response of [Get User Settings API](https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usersettings).
     *
     * @return $this
     */
    public function setAuthenticationOption($authentication_option)
    {
        $this->container['authentication_option'] = $authentication_option;

        return $this;
    }

    /**
     * Gets authentication_domains
     *
     * @return string
     */
    public function getAuthenticationDomains()
    {
        return $this->container['authentication_domains'];
    }

    /**
     * Sets authentication_domains
     *
     * @param string $authentication_domains Meeting authentication domains. This option, allows you to specify the rule so that Zoom users, whose email address contains a certain domain, can join the Webinar. You can either provide multiple domains, using a comma in between and/or use a wildcard for listing domains.
     *
     * @return $this
     */
    public function setAuthenticationDomains($authentication_domains)
    {
        $this->container['authentication_domains'] = $authentication_domains;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


